---

gravity:
  gunicorn:
    bind: '0.0.0.0:8080'
  celery:
    enable: false
    enable_beat: false

galaxy:
  database_connection: sqlite:///database/universe.sqlite?isolation_level=IMMEDIATE'
  install_database_connection: sqlite:///database/install.sqlite?isolation_level=IMMEDIATE'
  admin_users: brc@galaxyproject.org
  bootstrap_admin_api_key: c0ffee
  conda_auto_init: false
  file_path: SHARED_ROOT/objects
  job_working_directory: SHARED_ROOT/jobs
  #builds_file_path: null
  #len_file_path: null
  # not implemented as configurable, so we copy an empty shed_tool_conf.xml instead
  #shed_tools_dir: SHARED_ROOT/tools
  tool_data_path: SHARED_ROOT/tool-data
  #tool_data_table_config_path: /cvmfs/brc.galaxyproject.org/config/tool_data_table_conf.xml
  #tool_data_table_config_path: SHARED_ROOT/config/tool_data_table_conf.xml
  tool_data_table_config_path: tool_data_table_conf.xml
  container_resolvers:
    - cache_directory: /cvmfs/singularity.galaxyproject.org/all
      cache_directory_cacher_type: dir_mtime
      type: cached_mulled_singularity
  cleanup_job: never
  job_config:
    runners:
      local:
        load: galaxy.jobs.runners.local:LocalJobRunner
        workers: 1
      slurm:
        load: galaxy.jobs.runners.slurm:SlurmJobRunner
        drmaa_library_path: /usr/lib64/libdrmaa.so.1
    execution:
      default: tpv_dispatcher
      environments:
        tpv_dispatcher:
          runner: dynamic
          type: python
          function: map_tool_to_destination
          rules_module: tpv.rules
          tpv_config_files:
            - config/tpv.yml
